include "./en/graphics.asm"
include "./en/controls.asm"
include "./en/menu.asm"
include "./en/pause.asm"
include "./en/stageselect.asm"
include "./en/credits1.asm"
include "./en/credits2.asm"
include "./en/createdby.asm"
