//SNES MSU1
//Read
constant MSU_STATUS =   $2000
constant MSU_READ =     $2001
constant MSU_ID =       $2002
constant MSU_ID0 =      $2002
constant MSU_ID1 =      $2003
constant MSU_ID2 =      $2004
constant MSU_ID3 =      $2005
constant MSU_ID4 =      $2006
constant MSU_ID5 =      $2007

//Write
constant MSU_ADDR =     $2000
constant MSU_ADDR0 =    $2000
constant MSU_ADDR1 =    $2001
constant MSU_ADDR2 =    $2002
constant MSU_ADDR3 =    $2003
constant MSU_TRK =      $2004
constant MSU_TRK0 =     $2004
constant MSU_TRK1 =     $2005
constant MSU_VOL =      $2006
constant MSU_PLAY =     $2007
